---
name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Unit Tests
        run: npm run test:ci
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
      - name: eslint
        run: npm run lint
      - name: build for production
        run: npm run build
      - name: prettier
        run: npm run prettier:ci
